config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "hotels#index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  resources :hotels, only: [:index, :show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user # guest
  belongs_to :hotel

  validates :start_date, :end_date, presence: true
  validates :status, inclusion: { in: %w[pending confirmed cancelled] }

  validate :end_after_start
  before_save :calculate_total_price

  private

  def end_after_start
    return if end_date.blank? || start_date.blank?

    if end_date < start_date
      errors.add(:end_date, "must be after the start date")
    end
  end

  def calculate_total_price
    return unless start_date && end_date && hotel&.price_per_night

    days = (end_date - start_date).to_i
    self.total_price = days * hotel.price_per_night
  end
end

app/models/hotel.rb
class Hotel < ApplicationRecord
  # Associations
  belongs_to :user # host
  has_many :bookings, dependent: :destroy
  # has_many_attached :photos

  # Validations
  validates :name, :description, :address, :price_per_night, presence: true
  validates :price_per_night, numericality: { greater_than: 0 }

  # Instance methods
  def formatted_price
    # Displays something like "€89.95" or "$89.95"
    # hotel.formatted_price => "€89.95"
    sprintf("€%.2f", price_per_night)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  enum role: { host: 0, guest: 1 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/hotels_controller.rb
class HotelsController < ApplicationController
  def index
    if params[:query].present?
      @hotels = Hotel.where("address ILIKE ?", "%#{params[:query]}%")
    else
      @hotels = Hotel.all
    end
  end

  def show
    @hotel = Hotel.find(params[:id])
  end

  def new
    @hotel = Hotel.new
  end

  def create
    @hotel = Hotel.new()
    @hotel.save
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/hotels/_hotels_list.html.erb
<div class="hotel-grid container">
  <div class="row g-4">
    <% hotels.each do |hotel| %>
      <div class="col-12 col-sm-6 col-lg-3">
        <%= link_to hotel_path(hotel), class: "text-decoration-none text-dark" do %>
          <div class="card hotel-card h-100 border-2 border-dark shadow-sm">
            <div class="hotel-image">
              <% if hotel.photos.attached? %>
                <%= cl_image_tag hotel.photos.first.key,
                      height: 180,
                      width: 300,
                      crop: :fill,
                      gravity: :center,
                      loading: "lazy",
                      class: "img-fluid rounded-top" %>
              <% else %>
                <span class="text-muted">Hotel Image</span>
              <% end %>
            </div>
            <div class="card-body">
              <h5 class="fw-bold mb-1"><%= hotel.name %></h5>
              <p class="text-muted small mb-1"><%= hotel.address %></p>
              <p class="fw-semibold mb-0"><%= hotel.formatted_price %> / night</p>
            </div>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

app/views/hotels/index.html.erb
  <!-- Hero section -->
  <section class="hero-section-home position-relative text-white  shadow-sm">
    <div class="container">
      <div class="row justify-content-between align-items-center">
        <!-- Left: Welcome text -->
        <div class="col-lg-6 col-md-8 mx-auto mx-lg-0 text-start text-lg-start">
          <h1 class="fw-bold mt-4 text-dark">Find the perfect dog hotel</h1>
          <p class="fs-5 text-black">
            Book unique dog hotels and <br>experiences for your furry friend.
          </p>
        </div>
      </div>
    </div>
  </section>


  <section class="hotels-list py-5 my-4">
    <div id="hotels-list-container">
        <%= render "hotels_list", hotels: @hotels %>
    </div>
  </section>

app/views/hotels/new.html.erb
<div class="container">
    <h1>Post your hotel here</h1>

    <%= simple_form_for @hotel do |f| %>
        <%= f.input :name %>
        <%= f.input :description%>
        <%= f.input :address%>
        <%= f.input :price_per_night%>
        <%= f.button :submit %>
    <% end %>
</div>

app/views/hotels/show.html.erb
<h1><%= @hotel.name %></h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Pawbnb</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="icon" href="<%= asset_path 'favicon.png' %>" type="image/x-icon">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="d-flex flex-column min-vh-100">
  <%= render "shared/navbar" %>

  <main class="flex-grow-1">
      <%= yield %>
  </main>

  <%= render "shared/footer" %>
</body>

</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/shared/_footer.html.erb
<footer class="footer footer-expand-lg mt-auto p-3 border-top">
  <div class="container-fluid d-flex flex-column flex-md-row justify-content-between align-items-center text-muted small">
    <div class="mb-2 mb-md-0 d-flex align-items-center footer-copyright text-light">
      <span>© <%= Time.current.year %> <i class="fa-solid fa-paw paw me-1"></i><span class="pawbnb-logo">paw</span><span class="pawbnb-logo-light">bnb</span> — All rights reserved</span>
    </div>
    <div>
      <a href="#" class="text-decoration-none text-light me-3">About</a>
      <a href="#" class="text-decoration-none text-light me-3">Contact</a>
      <a href="#" class="text-decoration-none text-light">Privacy</a>
    </div>
  </div>
</footer>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg p-4 shadow-lg">
  <div class="container-fluid d-flex justify-content-between align-items-center">

    <!-- Left: Brand -->
    <%= link_to root_path, class: "text-decoration-none" do %>
      <div class="logo d-flex align-items-center">
        <i class="fa-solid fa-paw paw me-1 text-light"></i>
        <span class="pawbnb-logo text-light">paw</span>
        <span class="pawbnb-logo-light text-light">bnb</span>
      </div>
    <% end %>

    <!-- Center: Search bar -->
    <% if current_page?(root_path) %>
      <%= form_with url: root_path, method: :get, local: false, class: "d-flex position-relative mx-auto search-bar" do %>
        <%= text_field_tag :query, params[:query], class: "form-control rounded-pill ps-4 pe-5", placeholder: "Where?" %>
        <button class="btn position-absolute end-0 top-0 bottom-0 me-2 border-0 bg-transparent" type="submit">
          <i class="fa-solid fa-magnifying-glass text-secondary"></i>
        </button>
      <% end %>
    <% end %>
    <!-- Right: Login -->
    <% if user_signed_in? %>
      <%= link_to "Sign Out", destroy_user_session_path, data: { turbo_method: :delete }, class: "btn btn-outline-light fw-bold" %>
    <% else %>
      <%= link_to "Login", new_user_session_path, class: "btn btn-outline-light fw-bold" %>
    <% end %>
  </div>
</nav>